name: Deploy Bicep file
on: [push]
env:
  resourceGroupName: az104trainingdemo
  resourceGroupLocation: eastus
  webapplicationName: az10408augustdemo
  webapplicationlocation: eastus
  webappserviceplanname : az104appserviceplan
  

jobs:
  Chckout-code:
    runs-on: ubuntu-latest
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
            
      - name: Checkout code
        uses: actions/checkout@main

  Create-Resource-Group: 
    needs: [Chckout-code]
    runs-on: ubuntu-latest
    steps:    

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.GitHubActionsCrednetialcontri}}
        
              
      - name: Create a Resourcegroup for web deployment
        uses: Azure/CLI@v1
        with:
          inlineScript: |
                az group create -l $resourceGroupLocation -n $resourceGroupName

  Create-Web-Application: 
    needs: [Create-Resource-Group]
    runs-on: ubuntu-latest
    steps:    

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.GitHubActionsCrednetialcontri}}

      - name: Create a  app service plan
        uses: Azure/CLI@v1
        with:
          inlineScript: |
                        az appservice plan create --name $webappserviceplanname  --resource-group $resourceGroupName  --location $webapplicationlocation --sku S1
 
      - name: Create a  webapplication
        uses: Azure/CLI@v1
        with:
          inlineScript: |
                        az webapp create -g $resourceGroupName -p $webappserviceplanname -n $webapplicationName   

  Deploy-Static-website-html-using-wep up: 
    needs: [Create-Resource-Group]
    runs-on: ubuntu-latest
    steps:    

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.GitHubActionsCrednetialcontri}}

      
 
      - name: Create a  webapplication
        uses: Azure/CLI@v1
        with:
          inlineScript: |
                        az webapp create -g $resourceGroupName -p $webappserviceplanname -n $webapplicationName   